from arho_feature_template.qgis_plugin_tools.tools.exceptions import QgsPluginException


class AuthConfigException(QgsPluginException):
    pass
